# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Running CI

on:
  push:
    branches: master

jobs:
  UnitTesting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 使用 Node.js 12.x
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
      - name: 全域安裝 nyc
        run: npm i -g nyc
      - name: 套件安裝
        run: npm install
      - name: 執行測試
        run: npm run nyc
      - name: 更新測試覆蓋率
        run: npm run coverage
